/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pat_crous_dwayne;

import javax.swing.ImageIcon;

/**
 *
 * @author dwayne
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public MainMenuGUI() {
        initComponents();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDisplayAllBooks = new javax.swing.JButton();
        btnSortByTitle = new javax.swing.JButton();
        btnSortByAuthor = new javax.swing.JButton();
        btnAddABook = new javax.swing.JButton();
        btnSearchByTitle = new javax.swing.JButton();
        BtnSearchByISBN = new javax.swing.JButton();
        btnCalculateFine = new javax.swing.JButton();
        btnValidateISBN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblGreeting = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System | Dwayne Crous");
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Library Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 42));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Developed By Dwayne Crous");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, -1));

        btnDisplayAllBooks.setBackground(new java.awt.Color(176, 181, 179));
        btnDisplayAllBooks.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnDisplayAllBooks.setForeground(new java.awt.Color(0, 0, 0));
        btnDisplayAllBooks.setText("Display All Books");
        btnDisplayAllBooks.setToolTipText("Takes you to a window where you can view all of the books on the system.");
        btnDisplayAllBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllBooksActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayAllBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 210, 60));

        btnSortByTitle.setBackground(new java.awt.Color(176, 181, 179));
        btnSortByTitle.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSortByTitle.setForeground(new java.awt.Color(0, 0, 0));
        btnSortByTitle.setText("Sort By Title");
        btnSortByTitle.setToolTipText("Takes you to a window where you can sort all of the books in alphabetical order by title.");
        btnSortByTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByTitleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSortByTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 210, 60));

        btnSortByAuthor.setBackground(new java.awt.Color(176, 181, 179));
        btnSortByAuthor.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSortByAuthor.setForeground(new java.awt.Color(0, 0, 0));
        btnSortByAuthor.setText("Sort By Author");
        btnSortByAuthor.setToolTipText("Takes you to a window where you can sort books by the authors name.\\");
            btnSortByAuthor.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSortByAuthorActionPerformed(evt);
                }
            });
            getContentPane().add(btnSortByAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 210, 60));

            btnAddABook.setBackground(new java.awt.Color(176, 181, 179));
            btnAddABook.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            btnAddABook.setForeground(new java.awt.Color(0, 0, 0));
            btnAddABook.setText("+ Add a Book");
            btnAddABook.setToolTipText("Takes you to a window where you can add a book into the system.");
            btnAddABook.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAddABookActionPerformed(evt);
                }
            });
            getContentPane().add(btnAddABook, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 210, 60));

            btnSearchByTitle.setBackground(new java.awt.Color(176, 181, 179));
            btnSearchByTitle.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            btnSearchByTitle.setForeground(new java.awt.Color(0, 0, 0));
            btnSearchByTitle.setText("Search By Title");
            btnSearchByTitle.setToolTipText("Takes you to a window where you can search for a book by Title.");
            btnSearchByTitle.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSearchByTitleActionPerformed(evt);
                }
            });
            getContentPane().add(btnSearchByTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 210, 60));

            BtnSearchByISBN.setBackground(new java.awt.Color(176, 181, 179));
            BtnSearchByISBN.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            BtnSearchByISBN.setForeground(new java.awt.Color(0, 0, 0));
            BtnSearchByISBN.setText("Search By ISBN");
            BtnSearchByISBN.setToolTipText("Takes you to a window where you can search for a book by ISBN.");
            BtnSearchByISBN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnSearchByISBNActionPerformed(evt);
                }
            });
            getContentPane().add(BtnSearchByISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 210, 60));

            btnCalculateFine.setBackground(new java.awt.Color(176, 181, 179));
            btnCalculateFine.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            btnCalculateFine.setForeground(new java.awt.Color(0, 0, 0));
            btnCalculateFine.setText("Calculate Fine");
            btnCalculateFine.setToolTipText("Takes you to a window where you can calculate fines.");
            btnCalculateFine.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCalculateFineActionPerformed(evt);
                }
            });
            getContentPane().add(btnCalculateFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 210, 60));

            btnValidateISBN.setBackground(new java.awt.Color(176, 181, 179));
            btnValidateISBN.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            btnValidateISBN.setForeground(new java.awt.Color(0, 0, 0));
            btnValidateISBN.setText("Validate ISBN");
            btnValidateISBN.setToolTipText("Takes you to a window where you can validate ISBN numbers.");
            btnValidateISBN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnValidateISBNActionPerformed(evt);
                }
            });
            getContentPane().add(btnValidateISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, 60));

            jLabel3.setForeground(new java.awt.Color(0, 0, 0));
            jLabel3.setText("Dwayne Crous Development © 2024");
            getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

            jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(0, 0, 0));
            jLabel4.setText("What would you like to do today?");
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

            jPanel1.setBackground(new java.awt.Color(81, 113, 165));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            lblGreeting.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
            lblGreeting.setForeground(new java.awt.Color(0, 0, 0));
            lblGreeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblGreeting.setText("Welcome");
            jPanel1.add(lblGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 170, 50));

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

            jPanel2.setBackground(new java.awt.Color(81, 113, 165));
            getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 950, 100));

            jPanel3.setBackground(new java.awt.Color(152, 185, 171));
            getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 410));

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayAllBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllBooksActionPerformed
        // TODO add your handling code here:
        DisplayAllBooksGUI dabGui = new DisplayAllBooksGUI();
        dabGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDisplayAllBooksActionPerformed

    private void btnSortByTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByTitleActionPerformed
        // TODO add your handling code here:
        SortByTitleGUI sbtGUI = new SortByTitleGUI();
        sbtGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSortByTitleActionPerformed

    private void btnSortByAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByAuthorActionPerformed
        // TODO add your handling code here:
        SortByAuthorGUI sbaGUI = new SortByAuthorGUI();
        sbaGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSortByAuthorActionPerformed

    private void btnValidateISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateISBNActionPerformed
        // TODO add your handling code here:
        ValidateISBNGUI vISBNGUI = new ValidateISBNGUI();
        vISBNGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnValidateISBNActionPerformed

    private void btnCalculateFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateFineActionPerformed
        // TODO add your handling code here:
        CalculateFineGui cfGUI = new CalculateFineGui();
        cfGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCalculateFineActionPerformed

    private void btnAddABookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddABookActionPerformed
        // TODO add your handling code here:
        AddBooksGUI abGUI = new AddBooksGUI();
        abGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddABookActionPerformed

    private void btnSearchByTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByTitleActionPerformed
        // TODO add your handling code here:
        SearchByTitleGUI searchByTitleGUI = new SearchByTitleGUI();
        searchByTitleGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSearchByTitleActionPerformed

    private void BtnSearchByISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchByISBNActionPerformed
        // TODO add your handling code here:
        SearchByISBNGUI searchBtISBNGUI = new SearchByISBNGUI();
        searchBtISBNGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnSearchByISBNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }
    
    private void setAppIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/Square71x71Logo.scale-100.png"));
        setIconImage(icon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSearchByISBN;
    private javax.swing.JButton btnAddABook;
    private javax.swing.JButton btnCalculateFine;
    private javax.swing.JButton btnDisplayAllBooks;
    private javax.swing.JButton btnSearchByTitle;
    private javax.swing.JButton btnSortByAuthor;
    private javax.swing.JButton btnSortByTitle;
    private javax.swing.JButton btnValidateISBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblGreeting;
    // End of variables declaration//GEN-END:variables
}
