/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pat_crous_dwayne;

import javax.swing.ImageIcon;

/**
 *
 * @author dwayne
 */
public class SortByAuthorGUI extends javax.swing.JFrame {

    /**
     * Creates new form SortByAuthorGUI
     */
    public SortByAuthorGUI() {
        initComponents();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDisplaySortedBooks = new javax.swing.JButton();
        btnBackToMainMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSortByAuthor = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System | Dwayne Crous");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Library Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 330, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Developed By Dwayne Crous");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 40));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Books Sorted according to Authors Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 370, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dwayne Crous Development © 2024");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        btnDisplaySortedBooks.setBackground(new java.awt.Color(176, 181, 179));
        btnDisplaySortedBooks.setForeground(new java.awt.Color(0, 0, 0));
        btnDisplaySortedBooks.setText("Display Sorted books");
        btnDisplaySortedBooks.setToolTipText("Displays all of the books in alphabetical order according to the Authors first name.");
        btnDisplaySortedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySortedBooksActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplaySortedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, 60));

        btnBackToMainMenu.setBackground(new java.awt.Color(176, 181, 179));
        btnBackToMainMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnBackToMainMenu.setText("Back to Main Menu");
        btnBackToMainMenu.setToolTipText("When this button is clicked you go back to the main menu.");
        btnBackToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, 60));

        txaSortByAuthor.setBackground(new java.awt.Color(176, 181, 179));
        txaSortByAuthor.setColumns(20);
        txaSortByAuthor.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaSortByAuthor.setForeground(new java.awt.Color(0, 0, 0));
        txaSortByAuthor.setRows(5);
        jScrollPane1.setViewportView(txaSortByAuthor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 960, 560));

        jPanel1.setBackground(new java.awt.Color(81, 113, 165));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 90));

        jPanel2.setBackground(new java.awt.Color(81, 113, 165));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1350, 100));

        jPanel3.setBackground(new java.awt.Color(152, 185, 171));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1350, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainMenuActionPerformed
        // TODO add your handling code here:
        MainMenuGUI menuGUI = new MainMenuGUI();
        menuGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMainMenuActionPerformed

    private void btnDisplaySortedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySortedBooksActionPerformed
        // TODO add your handling code here:
        MANAGER_CLASS mc = new MANAGER_CLASS();
        mc.sortAuthor();
        txaSortByAuthor.setText(mc.toString());
    }//GEN-LAST:event_btnDisplaySortedBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortByAuthorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortByAuthorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortByAuthorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortByAuthorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortByAuthorGUI().setVisible(true);
            }
        });
    }
    
    private void setAppIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/Square71x71Logo.scale-100.png"));
        setIconImage(icon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMainMenu;
    private javax.swing.JButton btnDisplaySortedBooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaSortByAuthor;
    // End of variables declaration//GEN-END:variables
}
